CREATE DATABASE XYZ_company;

USE XYZ_company;
CREATE TABLE EMPLOYEE_INFO (Id INT PRIMARY KEY,  Name VARCHAR(50), Salary INT NOT NULL);

INSERT INTO EMPLOYEE_INFO VALUES ( 1 , "vaidehi" , 50000 );
INSERT INTO EMPLOYEE_INFO VALUES ( 2 , "Ashwini" , 30000 );
INSERT INTO EMPLOYEE_INFO VALUES ( 3 , "Priya" , 40000 );

SELECT * FROM EMPLOYEE_INFO;